//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21752342814933766938172121674976879111362417653261522357855816893656462449168377359285244818489723869987861247912289729579296691684761143544956991583942215236568961875851755854977946147178746464675227699149925227227137557479769948569788884399379821111382536722699575759474473273939756348992714667963596189765734743169489599125771443348193383566159843593541134749392569865481578359825844394454173219857919349341442148282229689541561169341622222354651397342928678496478671339383923769856425795211323673389723181967 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DATA1 {
            get {
                return ResourceManager.GetString("DATA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70,66,255,2,48,0,54,48,80,141,244,254,160,108,1,41.
        /// </summary>
        internal static string DATA10 {
            get {
                return ResourceManager.GetString("DATA10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 798	1976	1866	1862	559	1797	1129	747	85	1108	104	2000	248	131	87	95
        ///201	419	336	65	208	57	74	433	68	360	390	412	355	209	330	135
        ///967	84	492	1425	1502	1324	1268	1113	1259	81	310	1360	773	69	68	290
        ///169	264	107	298	38	149	56	126	276	45	305	403	89	179	394	172
        ///3069	387	2914	2748	1294	1143	3099	152	2867	3082	113	145	2827	2545	134	469
        ///3885	1098	2638	5806	4655	4787	186	4024	2286	5585	5590	215	5336	2738	218	266
        ///661	789	393	159	172	355	820	891	196	831	345	784	65	971	396	234
        ///4095	191	4333	161	3184	193	4830	4153	2070	37 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DATA2 {
            get {
                return ResourceManager.GetString("DATA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 368078.
        /// </summary>
        internal static string DATA3 {
            get {
                return ResourceManager.GetString("DATA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bdwdjjo avricm cjbmj ran lmfsom ivsof
        ///mxonybc fndyzzi gmdp gdfyoi inrvhr kpuueel wdpga vkq
        ///bneh ylltsc vhryov lsd hmruxy ebnh pdln vdprrky
        ///fumay zbccai qymavw zwoove hqpd rcxyvy
        ///bcuo khhkkro mpt dxrebym qwum zqp lhmbma esmr qiyomu
        ///qjs giedut mzsubkn rcbugk voxk yrlp rqxfvz kspz vxg zskp
        ///srceh xdwao reshc shecr
        ///dcao isz wwse bbdgn ewsw qkze pwu
        ///lbnvl lviftmr zqiv iadanl fdhrldn dlaani lxy dhfndrl fkoukx
        ///raovmz pdysjsw hqps orsyqw rrwnzcz vrzoam jjljt
        ///wgt gzi icpwp qeefgbe msadakj jbbrma sbj dufuujx zex
        ///cfzx  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DATA4 {
            get {
                return ResourceManager.GetString("DATA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 2 2 -2 -2 -2 1 2 2 -1 -4 -8 -7 -11 0 -13 -8 -7 -13 -11 -15 -4 -10 -10 -22 -22 -1 -9 1 2 -23 -4 -31 -3 2 -34 -28 -28 -16 -1 -34 -13 -25 1 -14 -40 -11 -32 -25 -17 -43 -23 -3 -52 -31 -8 -15 -48 -13 -56 -37 -24 -25 -47 -38 0 -35 -65 -63 -40 -18 -55 -11 -8 -18 -53 -39 -20 0 -6 -75 -22 -36 -71 -61 -74 -11 -14 -35 -54 -41 -59 -51 -45 -62 -53 -8 -26 -22 -16 -66 -87 -11 -59 -9 -44 -73 -76 -3 -78 -4 -45 -10 -38 -20 -102 -114 -44 -21 -111 -118 0 -80 -65 -28 -51 -95 -42 -31 -41 -98 -39 -89 -116 -115 -30 -68 -52 -21 - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DATA5 {
            get {
                return ResourceManager.GetString("DATA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0	5	10	0	11	14	13	4	11	8	8	7	1	4	12	11.
        /// </summary>
        internal static string DATA6 {
            get {
                return ResourceManager.GetString("DATA6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nzyiue (57)
        ///pdmkag (39)
        ///bogbg (13)
        ///nubay (45)
        ///dukzh (17)
        ///kpjxln (44) -&gt; dzzbvkv, gzdxgvj, wsocb, jidxg
        ///cxjyxl (83)
        ///vusplt (151) -&gt; mcfst, orrwx
        ///mxrfq (98)
        ///bdoez (62)
        ///vrajpg (78)
        ///qzsowpu (90)
        ///nrxoha (51)
        ///xtjrkv (351) -&gt; jlbhafs, pyocxtt
        ///rlnii (18986) -&gt; xjosf, ljvpv, wkumzkr
        ///ddrrgp (23)
        ///wladmn (42)
        ///ryskzh (209) -&gt; wsyya, xbqpjo
        ///jbjkp (34)
        ///fnfiur (86)
        ///zxzkl (82)
        ///hbmxey (1869) -&gt; khkuxc, mjuwde, tztycfl, miauii
        ///zjyqcfa (97)
        ///zbtck (48)
        ///mgsasl (39)
        ///cemygp (34)
        ///iolrkmv (139) -&gt; rntjx, itxtmhb
        ///jzmqzl (1446) -&gt; ppt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DATA7 {
            get {
                return ResourceManager.GetString("DATA7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdj dec 558 if r &lt;= 8
        ///cpv inc 669 if csu &gt;= -6
        ///ke dec 312 if pep != 0
        ///sdj inc -97 if bs == 0
        ///nj inc -593 if hp &lt; 1
        ///rcb inc -121 if t != 0
        ///moe inc -437 if vt &gt; -7
        ///n dec 865 if t == 0
        ///dtf dec 137 if u != 1
        ///cpv inc -625 if ke == 0
        ///zx inc 410 if nwg &lt; 8
        ///hp dec -263 if nj &gt;= -585
        ///ib dec 335 if ifd &gt; -8
        ///pmp inc -432 if sdj &lt;= -648
        ///vt inc 612 if vt &gt; -4
        ///pep inc -244 if pep == 9
        ///zx dec 237 if pmp &lt;= -433
        ///sdj inc 805 if cpv &gt; 39
        ///cpv dec -110 if nwg != 4
        ///n inc -644 if yk == 0
        ///zx dec -522 if ke &gt; -8
        ///cpv inc -360 if oj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DATA8 {
            get {
                return ResourceManager.GetString("DATA8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{{{&lt;!!!&gt;},&lt;!e!!!&apos;ue!o!!!&gt;&quot;oo&lt;u!}&lt;&lt;{&gt;},{{{}},{&lt;!&gt;},&lt;&apos;&gt;,{&lt;!!&quot;!!!&gt;&quot;u!!!&gt;!!!&gt;,&lt;&quot;!&gt;,&lt;!&gt;},&lt;}!!}!!!&gt;{&gt;}},{{&lt;&quot;!&gt;}}!&apos;!!u!!!!e!!!&gt;&gt;}}}},{{{&lt;!&gt;&gt;}},{{{&lt;{{!!,&gt;},{&lt;u!!e&apos;!&gt;},&lt;&gt;}}},{&lt;,o!!!&quot;&quot;a!&gt;},&lt;!&gt;},&lt;&lt;}&gt;,{&lt;!!!!,,!&gt;,&lt;!&gt;},&lt;&quot;!!!&gt;u&gt;}}},{{{&lt;}{!&lt;{i!&gt;&gt;}},{{}},{{},&lt;!&gt;,&lt;!&gt;,&lt;!&gt;!!,&lt;!!!!{}!!i&gt;}}},{{},{{{}}},{{&lt;ae{&gt;,{}}},{{&lt;!!!!&quot;&gt;,&lt;{&apos;}!!},&lt;!&gt;a,!&gt;!!!&gt;{!!e&gt;},{{&lt;!ao!!i!&apos;!&gt;,&lt;!!o&gt;,&lt;&apos;e}!!!&gt;!!!&gt;e&apos;!!u{&gt;},&lt;&quot;,&apos;i!!!&gt;{&gt;},{&lt;uai,!!{!&gt;},&lt;uu!!e&gt;}}},{{{{{&lt;!!,a!&gt;&gt;}}}},{},{{{{{{},{{&lt;au&lt;,!!iuu!!!!!&gt;,&lt;&gt;}}},{&lt;i!&gt;,&lt;!&gt;},&lt;!!&apos;iu{!!o&quot;{i,i}!{{&gt;}},{},{{&lt;a!&gt;a&quot;!! [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DATA9 {
            get {
                return ResourceManager.GetString("DATA9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Advent of Code 2017
        ///	http://adventofcode.com/2017
        ///	author: @mrzepisko
        ///	https://github.com/rzmarcin/advent-of-code_2017.
        /// </summary>
        internal static string INTRO_TEXT {
            get {
                return ResourceManager.GetString("INTRO_TEXT", resourceCulture);
            }
        }
    }
}
