//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21752342814933766938172121674976879111362417653261522357855816893656462449168377359285244818489723869987861247912289729579296691684761143544956991583942215236568961875851755854977946147178746464675227699149925227227137557479769948569788884399379821111382536722699575759474473273939756348992714667963596189765734743169489599125771443348193383566159843593541134749392569865481578359825844394454173219857919349341442148282229689541561169341622222354651397342928678496478671339383923769856425795211323673389723181967 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DATA1 {
            get {
                return ResourceManager.GetString("DATA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 798	1976	1866	1862	559	1797	1129	747	85	1108	104	2000	248	131	87	95
        ///201	419	336	65	208	57	74	433	68	360	390	412	355	209	330	135
        ///967	84	492	1425	1502	1324	1268	1113	1259	81	310	1360	773	69	68	290
        ///169	264	107	298	38	149	56	126	276	45	305	403	89	179	394	172
        ///3069	387	2914	2748	1294	1143	3099	152	2867	3082	113	145	2827	2545	134	469
        ///3885	1098	2638	5806	4655	4787	186	4024	2286	5585	5590	215	5336	2738	218	266
        ///661	789	393	159	172	355	820	891	196	831	345	784	65	971	396	234
        ///4095	191	4333	161	3184	193	4830	4153	2070	37 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DATA2 {
            get {
                return ResourceManager.GetString("DATA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 368078.
        /// </summary>
        internal static string DATA3 {
            get {
                return ResourceManager.GetString("DATA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bdwdjjo avricm cjbmj ran lmfsom ivsof
        ///mxonybc fndyzzi gmdp gdfyoi inrvhr kpuueel wdpga vkq
        ///bneh ylltsc vhryov lsd hmruxy ebnh pdln vdprrky
        ///fumay zbccai qymavw zwoove hqpd rcxyvy
        ///bcuo khhkkro mpt dxrebym qwum zqp lhmbma esmr qiyomu
        ///qjs giedut mzsubkn rcbugk voxk yrlp rqxfvz kspz vxg zskp
        ///srceh xdwao reshc shecr
        ///dcao isz wwse bbdgn ewsw qkze pwu
        ///lbnvl lviftmr zqiv iadanl fdhrldn dlaani lxy dhfndrl fkoukx
        ///raovmz pdysjsw hqps orsyqw rrwnzcz vrzoam jjljt
        ///wgt gzi icpwp qeefgbe msadakj jbbrma sbj dufuujx zex
        ///cfzx  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DATA4 {
            get {
                return ResourceManager.GetString("DATA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DATA5 {
            get {
                return ResourceManager.GetString("DATA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0	5	10	0	11	14	13	4	11	8	8	7	1	4	12	11.
        /// </summary>
        internal static string DATA6 {
            get {
                return ResourceManager.GetString("DATA6", resourceCulture);
            }
        }
    }
}
